#!/bin/bash

echo "Checking dependencies..."

if [ -d "/opt/lampp/" ]; then
    echo "XAMPP is installed."
else
    echo "XAMPP is not installed. Please install XAMPP to run this project."
    echo "command: sudo apt-get install xampp"
    echo "website -> https://www.apachefriends.org/index.html"
fi
